Classwork/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("view/", views.ClassworkView, name='classwork-view'),
    path("<int:test_id>/list/", views.SubmittedListView, name='submitted-view'),
    path("create/",views.CreateClassworkView, name='create-classwork-view'),
    path("<int:test_id>/edit/",views.EditClassworkView, name='edit-classwork-view'),
    path("<int:test_id>/download/",views.DownloadTestFile, name = "download-test-file"),
    path("<int:test_id>/change/",views.ChangeTestInformation, name = 'change-test-information'),
    path("<int:test_id>/do/",views.DoTestView,name='do-test'),
    path("<int:test_id>/upload/",views.UploadAssignmentview,name='upload-assignment'),
    path("<int:test_id>/edit/addwritten/",views.written_question_form,name='written-form'),
    path("<int:test_id>/edit/addmultiplechoice/",views.multiplechoice_form,name='multiplechoice-form'),
    path("<str:qid>/mcoform/",views.mco_form,name='mco-form'),
    path("<int:test_id>/delete/",views.DeleteTest,name='delete-classwork-view'),
    path("<int:test_id>/<int:qid>/delete",views.DeleteQuestion,name='delete-question-view'),
    path("<int:test_id>/<int:qid>/update",views.UpdateQuestion,name='update-question-view'),
    path("view/<int:studenttest_id>/",views.ViewStudentTest,name='view-student-test'),
    path("view/<int:studenttest_id>/download/",views.DownloadStudentFile,name='download-student-file')
]

Home/urls.py
from . import views
from django.urls import path,include

urlpatterns = [
    path('', views.GuestAnnouncement, name="guest-announcement-page"),
    path('user/', include("User.urls")),
    path('announcement/<int:announcement_id>', views.GuestAnnouncementPage, name='guest-announcement-viewpage'),
    path('about/', views.About, name='about'),
    path('about/talents', views.Talents, name='talents'),
    path('contact-us/', views.Contact, name='contact'),
    path('announcement/all/', views.GuestAnnouncementAll, name='guest-announcement-all'),
    path('announcement/search/', views.GuestAnnouncementSearch, name='guest-announcement-search'),
]

elearningplatform/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
import Courses.views as views
from django.views.static import serve


urlpatterns = [
    path('admin/', admin.site.urls,name="admin"),
    path('',include("Home.urls")),
    #path('user/',include("User.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_URL)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_URL)

Classwork/models.py
from django.db import models
import datetime
from django.db.models.deletion import CASCADE

# Create your models here.

class Test(models.Model):
  class_id = models.ForeignKey("Courses.Class",on_delete=CASCADE)
  test_description = models.TextField(null=True,blank=True)
  attached_file = models.FileField(null=True,blank=True,upload_to='tests/')
  test_name = models.CharField(max_length=100)
  publish_time = models.DateTimeField()
  end_time = models.DateTimeField()
  time_modified = models.DateTimeField(auto_now=True)
  available_time_after_deadline = models.DurationField(default=datetime.timedelta(hours=6)) # available for submission after deadline
  is_quiz = models.BooleanField(default=False)
  def __str__(self):
      return self.test_name 

class Question(models.Model):
  test_id = models.ForeignKey(Test,on_delete=CASCADE)
  is_written = models.BooleanField()  # true if written question, false if multiplechoice
  question = models.TextField()
  def __str__(self):
      return self.question

class MultipleChoiceOption(models.Model):
  question = models.ForeignKey(Question,on_delete=CASCADE)
  option = models.CharField(max_length=50)
  is_true = models.BooleanField()
  def __str__(self):
      return self.option
  
class StudentTest(models.Model):
  student_id = models.ForeignKey("User.student",on_delete=CASCADE)
  test_id = models.ForeignKey(Test,on_delete=CASCADE)
  submit_time = models.DateTimeField(auto_now_add=True)
  grade = models.FloatField(blank=True,null=True)
  is_overdue = models.BooleanField(default=False)

class StudentAnswer(models.Model):
  student_test = models.ForeignKey(StudentTest,on_delete=CASCADE)
  question = models.ForeignKey(Question,on_delete=CASCADE)
  written_ans = models.TextField(blank=True,null=True)
  choice_ans = models.ManyToManyField(MultipleChoiceOption,blank=True)
  
class StudentUpload(models.Model):
  studenttest = models.OneToOneField(StudentTest,on_delete=CASCADE)
  attached_file = models.FileField(upload_to='assignments/')
  file_description = models.TextField(null=True,blank=True)

Classwork/forms.py
from django import forms
from django.forms import widgets
from .models import *

class TestForm(forms.ModelForm):
  # publish_time = forms.DateTimeField(label='Publish time', widget=forms.DateTimeInput(attrs={'type': 'datetime-local'}))
  # end_time = forms.DateTimeField(label='End time', widget=forms.DateTimeInput(attrs={'type': 'datetime-local'}))
  
  class Meta:
    model = Test
    fields = [
      "test_name",
      "test_description",
      "attached_file",
      "publish_time",
      "end_time",
      "available_time_after_deadline",
      "is_quiz"
      ]
    # widgets={
    #   "publish_time":widgets.DateTimeInput(attrs={'type':'datetime-local'}),
    #   "end_time":forms.DateTimeInput(attrs={'type':'datetime-local'}),
    # }
    widgets={
      "publish_time":forms.DateTimeInput(format='%Y-%m-%d %H:%M:%S', attrs={'class':'datetimefield'}),
      "end_time":forms.DateTimeInput(format='%Y-%m-%d %H:%M:%S', attrs={'class':'datetimefield'}),
      "attached_file":forms.ClearableFileInput(attrs={'allow_multiple_selected': True}),
    }

class WrittenQuestionForm(forms.Form):
  question = forms.CharField(label='Question')

class MultipleChoiceQuestionForm(forms.Form):
  question = forms.CharField(label='Question')
  
class StudentUploadForm(forms.ModelForm):
  class Meta:
    model = StudentUpload
    fields = ["attached_file","file_description"]
    widgets={
      "file": forms.ClearableFileInput(attrs={'allow_multiple_selected': True}),
    }

class MultipleChoiceOptionForm(forms.Form):
  optionid = forms.CharField(widget=forms.HiddenInput,required=False)
  option = forms.CharField(label='Option')
  is_true = forms.BooleanField(label = "Is true",required=False,initial=False)

# class WrittenQuestionForm(forms.ModelForm):
#   class Meta:
#     model = Question
#     fields = ["question"]

# class MultipleChoiceQuestionForm(forms.ModelForm):
#   class Meta:
#     model = Question
#     fields = ["question"]

# class MultipleChoiceOptionForm(forms.ModelForm):
#   class Meta:
#     model = MultipleChoiceOption
#     fields = ["is_true","option"]

Classwork/views.py
import os
import zipfile
from datetime import timezone
from uuid import uuid4
from django.http.response import FileResponse, HttpResponse
from django.shortcuts import render
from User.views import CheckValidUser
from django.http import HttpResponseRedirect, Http404
from django.urls import reverse
from Courses.models import Class
from User.models import Lecturer, Student, User
from django.utils import timezone
from .models import *
from .forms import *
from django.conf import Settings, settings
# Create your views here.

def CheckValidUser(func):
    def decorate(*args, **kwargs):
        userID = kwargs['id']
        classID=kwargs['class_id']
        request = args[0]
        if request.user.id==None:
            return HttpResponseRedirect(reverse("login"))
        elif request.user.is_student():
            return HttpResponseRedirect(reverse('student-class-announcement-page',args=[userID,classID]))
        elif request.user.is_lecturer():
            user = Lecturer.objects.get(id=userID).user_id
        else:
            user = User.objects.get(id=userID)
        if request.user == user and request.user.is_authenticated:
            return func(*args, **kwargs)
        else:
            return HttpResponseRedirect(reverse("guest-announcement-page"))
    return decorate
  
def DownloadTestFile(request, id, class_id, test_id):
    test = Test.objects.get(id=test_id)
    # path = test.attached_file.url
    # file_path = str(settings.BASE_DIR).replace("\\","/") + path
    # if os.path.exists(file_path):
    #     with open(file_path, 'rb') as fh:
    #         response = HttpResponse(fh.read(), content_type="application/pdf")
    #         response['Content-Disposition'] = 'inline; filename=' + os.path.basename(file_path)
    #         return response
    # raise Http404
    file = test.attached_file.path
    response = FileResponse(open(file,'rb'))
    if response:
      return response
    else:
      return Http404

def DownloadStudentFile(request,id,class_id, studenttest_id):
    test = StudentTest.objects.get(id= studenttest_id).studentupload
    # path = test.attached_file.url
    # file_path = str(settings.BASE_DIR).replace("\\","/") + path
    # if os.path.exists(file_path):
    #     with open(file_path, 'rb') as fh:
    #         response = HttpResponse(fh.read(), content_type="application/pdf")
    #         response['Content-Disposition'] = 'inline; filename=' + os.path.basename(file_path)
    #         return response
    # raise Http404
    file = test.attached_file.path
    response = FileResponse(open(file,'rb'))
    if response:
      return response
    else:
      return Http404  
@CheckValidUser
def CreateClassworkView(request, id, class_id):
  context={'id':id,'class_id':class_id,"new":True}
  if request.method == 'POST':
    form = TestForm(request.POST,request.FILES)
    if(form.is_valid()):
      t = form.save(commit=False)
      t.class_id = Class.objects.get(id=class_id)
      t.save()
      return HttpResponseRedirect(reverse("lecturer-class-assignment-page",args=[id,class_id]))
  else:
    form = TestForm()
  context['form'] = form
  context['lecturer_class'] = Class.objects.get(id=class_id)
  return render(request, "Classwork/create-classwork.html",context)

@CheckValidUser
def ChangeTestInformation(request, id, class_id, test_id):
  test = Test.objects.get(id=test_id)

  if request.method == 'POST':
    form = TestForm(request.POST,request.FILES, instance=test)
    if(form.is_valid()):
      form.save()
      test.save()
      return HttpResponseRedirect(reverse("lecturer-class-assignment-page",args=[id,class_id]))
  else:  
    form = TestForm(instance=test)
    context= {"id":id,"class_id":class_id,"test_id":test_id,"form":form,"test":test}
    return render(request, "Classwork/create-classwork.html",context)


@CheckValidUser
def ClassworkView(request, id, class_id):
  lecturer = Lecturer.objects.get(id=id)
  c = Class.objects.get(id=class_id)
  context={'id':id,'class_id':class_id}
  tests = c.test_set.all()
  context['tests']=tests
  return render(request,'Classwork/view-classwork.html', context)

@CheckValidUser
def EditClassworkView(request, id, class_id , test_id):
  lecturer = Lecturer.objects.get(id=id)
  class_id = Class.objects.get(id=class_id)
  test = Test.objects.get(id=test_id)
  if request.method == "POST":
    print(request.POST)
  context = {'id':id,'class_id':class_id.id,'test':test,'test_id':test_id}
  return render(request,'Classwork/edit-classwork.html',context)

def UploadAssignmentview(request,id,class_id,test_id):
  studenttest= None
  done=False
  grade = None
  if request.user.is_lecturer():
    return HttpResponseRedirect(reverse("student-class-assignment-page",args=[id,class_id]),args=[id,class_id])
  t = Test.objects.get(id=test_id)
  if t.is_quiz:
    return HttpResponseRedirect(reverse("student-class-assignment-page",args=[id,class_id]),args=[id,class_id])
  now = timezone.localtime()+timezone.timedelta(hours=7)
  if not t.publish_time <= now:
    HttpResponseRedirect(reverse('student-class-announcement-page',args=[id,class_id]))
  if t.studenttest_set.filter(student_id=id,test_id=test_id).exists():
    studenttest = t.studenttest_set.get(student_id=id,test_id=test_id)
    done = True
    grade = studenttest.grade
  if request.method == "POST":
    isoverdue = t.end_time <= now+ t.available_time_after_deadline
    test = StudentTest(student_id=Student.objects.get(id=id),test_id=Test.objects.get(id=test_id),is_overdue=isoverdue)
    test.save()
    form = StudentUploadForm(request.POST,request.FILES)
    form.studenttest = StudentTest.objects.get(student_id=Student.objects.get(id=id),test_id=Test.objects.get(id=test_id))
    if form.is_valid():
      f=form.save(commit=False)
      f.studenttest = StudentTest.objects.get(student_id=Student.objects.get(id=id),test_id=Test.objects.get(id=test_id))
      f.save()
    return HttpResponseRedirect(reverse('upload-assignment',args=[id,class_id,test_id]))
  else:
    form = StudentUploadForm()
    if StudentTest.objects.filter(student_id=Student.objects.get(id=id),test_id=Test.objects.get(id=test_id)).exists():
      studenttest=StudentTest.objects.get(student_id=Student.objects.get(id=id),test_id=Test.objects.get(id=test_id))
    context={'test':Test.objects.get(id=test_id), "done":done, "id":id,"class_id":class_id,"grade":grade,"form":form,"studenttest":studenttest,"student_class":Class.objects.get(id=class_id)}
    return render(request,"Classwork/upload-assignment.html",context)

def DoTestView(request,id,class_id,test_id):
  done=False
  grade = None
  a=None
  if request.user.is_lecturer():
    return HttpResponseRedirect(reverse("student-class-assignment-page",args=[id,class_id]),args=[id,class_id])
  t = Test.objects.get(id=test_id)
  now = timezone.localtime()+timezone.timedelta(hours=7)
  if not t.publish_time <= now:
    HttpResponseRedirect(reverse('student-class-assignment-page',args=[id,class_id]))
  if t.studenttest_set.filter(student_id=id,test_id=test_id).exists():
    a = t.studenttest_set.get(student_id=id,test_id=test_id)
    done = True
    grade = a.grade
  if request.method == 'POST':
    # print(dict(request.POST.lists()))
    isoverdue = t.end_time <= now+ t.available_time_after_deadline
    test = StudentTest(student_id=Student.objects.get(id=id),test_id=Test.objects.get(id=test_id),is_overdue=isoverdue)
    test.save()
    for question, answer in dict(request.POST.lists()).items():
      if question != 'csrfmiddlewaretoken':
        q = Question.objects.get(id=int(question))
        a = StudentAnswer(student_test=test,question=q)
        a.save()
        if q.is_written:
          a.written_ans=answer[0]
        else:
          for mco in answer:
            a.choice_ans.add(MultipleChoiceOption.objects.get(id=int(mco)))
        a.save()
    return HttpResponseRedirect(reverse('do-test',args=[id,class_id,test_id]))
  context={'test':Test.objects.get(id=test_id), "done":done, "id":id,"class_id":class_id,"grade":grade,"student_class":Class.objects.get(id=class_id)}
  return render(request,"Classwork/do-test.html",context)

@CheckValidUser
def ViewStudentTest(request,id,class_id,studenttest_id):
  st = StudentTest.objects.get(id=studenttest_id)
  g = None
  if st.grade!=None:
    g = st.grade
  if request.method == "POST":
    grade = float(request.POST['grade'])
    if grade >= 0:
      st.grade = grade
      st.save()
    return HttpResponseRedirect(reverse("submitted-view",args=[id,class_id,st.test_id.id]))
  right_ans=0
  for ans in st.studentanswer_set.all():
    if not ans.question.is_written:
        q = ans.question.multiplechoiceoption_set.all()
        right = [answer for answer in q if answer.is_true]
        if(set(ans.choice_ans.all())==set(right)):
          right_ans+=1
  context = {"class_id":class_id, "id":id,"test":st,"right":right_ans,"grade":g,"lecturer_class":Class.objects.get(id=class_id)}
  return render(request,"Classwork/view-student-test.html",context)

@CheckValidUser
def written_question_form(request,id,class_id,test_id):
  form = MultipleChoiceQuestionForm()
  if request.method == 'POST':
    q = Question(question=request.POST['question'],is_written=True,test_id=Test.objects.get(id=test_id))
    q.save()
    return HttpResponseRedirect(reverse("edit-classwork-view",args=[id,class_id,test_id]))
  context={'form':form}
  return render(request,"Classwork/partials/partial-written-form.html",context)

@CheckValidUser
def multiplechoice_form(request,id,class_id,test_id):
  error=""
  form = MultipleChoiceQuestionForm()
  qid=str(uuid4())[:5]
  form.fields['q.'+qid]=form.fields['question']
  del form.fields['question']
  context = {'form':form,"id":id,"class_id":class_id,"qid":qid}
  if request.method == 'POST':
    questions,options,correctoptions = parseMultipleChoice(request)
    for k,v in questions.items():
      q = Question(question=v,is_written=False,test_id=Test.objects.get(id=test_id))
      q.save()
      for m,n in options.items():

Classwork/templates/Classwork/base-test.html
{% extends 'Home/index.html' %}
{% load static %}

{% block stylesheets %}
  <link rel="stylesheet" href="{% static 'Courses/base-student-class.css' %}">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
  <script src="https://cdn.jsdelivr.net/npm/flatpickr"></script>
<script>
    // This code activates flatpickr on fields with the 'datetimefield' class when the document has loaded
    window.addEventListener("DOMContentLoaded", function () {
        flatpickr(".datetimefield", {
            enableTime: true,
            enableSeconds: true,
            dateFormat: "Y-m-d H:i:S",
        });
    });
</script>
{% endblock %}

{% block main-content %}
  <article class="panel">
    <header>
      {% if user.user_type == 'Student' %}
        <h2>{{ student_class.course.name }} - {{ student_class.schedule }} - {{ student_class.sem_year }}</h2>
      {% elif user.user_type == 'Lecturer' %}
        <h2>{{ lecturer_class.course.name }} - {{ lecturer_class.schedule }} - {{ lecturer_class.sem_year }}</h2>
      {% endif %}

      {% if user.user_type == 'Student' %}
        <p>Instructor: {{ student_class.lecturer.user_id.full_name }}</p>
      {% endif %}
  <title>Document</title>
</header>
<body>
  {% block panel-content %}{% endblock panel-content %}
    <script>
      document.body.addEventListener('htmx:configRequest', (event) => {
          event.detail.headers['X-CSRFToken'] = '{{ csrf_token }}';
      })
  </script>
</body>
</article>
{% endblock %}

<!-- DUY 

Note: Đăng nhập vô lecturer account: loan.nguyen@lecturer.com,
                  student account: khoa.nguyen@student.com 
                  Môn Software Engineering - TUE Afternoon - Sem 1 - 2022

cái title tên môn học, instructor trên cùng của các page: 
  create-classwork.html, 
  delete-classwork.html,
  submitted-list.html,
  view-student-test.html,
  upload-assignment.html

Due Date, Submitted Time của các page:
  upload-assignment.html,
  view-student-course-performance.html,
  submitted-list.html,

Phần publish time, end time của các page:
  create-classwork.html - khi create new và khi edit luôn nha

Với lại t k biết chỉnh style cái checkbox Clear với Is quiz. Nếu đc m chỉnh sao cho nó nằm cạnh nhau giúp t với. 

Hết rồi thankss nhèoo -->

Classwork/templates/Classwork/create-classwork.html
{% extends 'Classwork/base-test.html' %}

{% load static %}

{% block title %}
  <title>{{ lecturer_class.course.name }} - {{ lecturer_class.schedule }} New Assignment</title>
{% endblock title %}

{% block stylesheets %}
  {{ block.super }}
  <link rel="stylesheet" href="{% static 'User/upload-assignment.css' %}">
  <link rel="stylesheet" href="{% static 'User/upload-announcement.css' %}">
  <script src="{% static 'User/upload-content.js' %}" defer></script>
{% endblock %}

{% block panel-content %}
<article>
  <div class="heading">
    <h3 class="title">New Test</h3>
  </div>
  <form action="." method = "POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{form.as_p}}
    <div>
      <!-- {% if not new %}
      <a href="{% url 'download-test-file' id class_id test_id %}">Download file</a>
      {%endif%} -->
      <!-- <p>
        Check the "is quiz" field if this is a quiz taken on the website or leave it unchecked if this is a file upload assignment
      </p> -->
      {% if test.is_quiz %}
      <a href="{% url 'edit-classwork-view' id class_id test_id%}">Change quiz questions</a>
      {% endif %}
      
      <!-- <button type="submit">Save Test</button> -->
      <div class="btn-container">
        <!-- {% if not new %}
        <form method='POST'>
          {%csrf_token%}
          <input class="btn-delete" type="Submit" value="Delete"/>
        </form>
        {%endif%} -->
        <div class="right-buttons">
        <input class="btn post" type="Submit" value="Post"/>
        <a class="btn cancel" href="{% url 'lecturer-class-assignment-page' id class_id %}">
          Cancel
        </a>
      </div>
      
    </div>
    </form>
</article>

{% endblock %}

Classwork/templates/Classwork/delete-classwork.html
{% extends 'Classwork/base-test.html'%}
{% load static %}
{% block title %}
  <title>{{ lecturer_class.course.name }} - {{ lecturer_class.schedule }} Edit announcement</title>
{% endblock title %}

{% block stylesheets %}
  {{ block.super }}
  <link rel="stylesheet" href="{% static 'User/upload-assignment.css' %}">
  <link rel="stylesheet" href="{% static 'User/upload-announcement.css' %}">
{% endblock %}

{% block panel-content %}
  <article>
  <form method='POST'>
    {%csrf_token%}
    <h2>Delete the test {{test.test_name}}</h2>
    <div class="btn-middle">
    <input class="btn-delete" type="submit" value="Delete">
      <a class="btn cancel" href="{% url 'lecturer-class-assignment-page' id class_id %}">
        Cancel
      </a>
    </div>
    
  </form>
  
</article>
{% endblock %}

Classwork/templates/Classwork/do-test.html
{% extends 'Classwork/base-test.html' %}
{% load static %}

{% block stylesheets %}
{{ block.super }}
<link rel="stylesheet" href="{% static 'User/base-upload.css' %}">
<link rel="stylesheet" href="{% static 'User/upload-announcement.css' %}">
<script src="{% static 'User/upload-content.js' %}" defer></script>
{% endblock %}

{% block panel-content %}
<article>
    <div class="heading">
        <h3>TEST NAME: {{test.test_name}}</h3>
    </div>
    
    <p>{{test.test_description}}</p>
    {% if not test.is_quiz %}
    <p><a href="{% url 'download-test-file' id class_id test.id%}"></a>Download test file</p>
    {% endif %}
    {% if not done %}
    <form method="POST" action="#">
        {%csrf_token%}
        {%for question in test.question_set.all %}
        <p>{{forloop.counter}}. {{question.question}}</p>
        {%if question.is_written%}
        <input name="{{question.id}}" type="text">
        {%else%}
        {%for option in question.multiplechoiceoption_set.all%}
        <div class="checkbox">
            <input type="checkbox" value="{{option.id}}" name="{{question.id}}">
            <label for="{{option.id}}">{{option.option}}</label>
        </div>

        {%endfor%}
        {%endif%}
        {%endfor%}
        <hr>
        <div><input type="submit" value='Submit test'></div>
    </form>
    {% else %}
    <div>
        <p>You have already done this test</p>
        <hr>
        {%if grade%}
        <p>Your grade is {{grade}}</p>
        {%else%}
        <p>Test is ungraded</p>
        {%endif%}
        <a href="{% url 'student-class-assignment-page' id class_id%}">Return</a>
    </div>
    {% endif %}
</article>
{% endblock %}

Classwork/templates/Classwork/edit-classwork.html
{% extends 'Classwork/base-test.html' %}
{% load static %}

{% block title %}
  <title>{{ lecturer_class.course.name }} - {{ lecturer_class.schedule }} New Assignment</title>
{% endblock title %}

{% block stylesheets %}
  {{ block.super }}
  <link rel="stylesheet" href="{% static 'User/upload-assignment.css' %}">
  <link rel="stylesheet" href="{% static 'User/upload-announcement.css' %}">
  <script src="{% static 'User/upload-content.js' %}" defer></script>
{% endblock %}
{%block panel-content%}
<article>
  <form method = "POST">
  {% csrf_token %}
  <div id="questionform">
    {% for question in test.question_set.all%}
    <p>{{forloop.counter}}.{{question.question}}</p>
    <button type="button" onclick="location.href='{% url 'update-question-view' id class_id test.id question.id %}'">Update</button>
    <button type="button" onclick="location.href='{% url 'delete-question-view' id class_id test.id question.id %}'">Delete</button>
    {% if question.is_written %}
    {% else %}
    {% for option in question.multiplechoiceoption_set.all %}
    <ul>
    {%if option.is_true%}
      <li><strong>{{option.option}}</strong></li>
    {%else%}
      <li>{{option.option}}</li>
    {%endif%}
    </ul>
    {%endfor%}
    {%endif%}
    {%endfor%}
  </div>
  <div>
    <!-- <button hx-get="{% url 'written-form' id class_id test.id%}" hx-swap = "beforeend" hx-target="#questionform">Add new written question</button>
    <button hx-get="{% url 'multiplechoice-form' id class_id test.id %}" hx-swap = "beforeend" hx-target="#questionform">Add new multiple choice question</button>  -->
    <a href="{% url 'written-form' id class_id test.id%}">Add new written question</a>
    <a href="{% url 'multiplechoice-form' id class_id test.id %}">Add new multiple choice question</a>
  </div>
  <!-- <div>
    <button type="submit">
      Save
    </button>
  </div> -->
  </form>
  <div>
    <a href="{% url 'lecturer-class-assignment-page' id class_id%}">Go back to classworks view</a>
  </div>
</article>

{% endblock %}

Classwork/templates/Classwork/update-question.html
{%extends 'Classwork/base-test.html'%}
{%block panel-content%}
<article>
  <form method="POST">
  {% csrf_token %}
  <label for="question">Question:  </label><input type="text" value="{{question.question}}" id="question" name=question>
  {%if question.is_written%}
  <button type="submit">Update</button>
  {%else%}
  {%for option in question.multiplechoiceoption_set.all%}
  <p>
  <label for="option.id">Option:  </label>
  <input type="text" value="{{option.option}}" id="{{option.id}}" name="{{option.id}}">
  <label>Is true: </label>
  {%if option.is_true%}
  <input type="checkbox" checked id="{{option.id}}" name="{{option.id}}">
  {%else%}
  <input type="checkbox" id="{{option.id}}" name="{{option.id}}">
  </p>
  {%endif%}
  {%endfor%}
  {%endif%}
  <button type="submit">Save</button>
</form>
</article>

{%endblock %}

Classwork/templates/Classwork/view-classwork.html
{% extends 'Classwork/base-test.html' %}
{%block body%}

    {% for test in tests %}
    <h3>{{test.test_name}}   <a href="{% url 'edit-classwork-view' id class_id test.id %}">EDIT</a>  <a href="{%url 'delete-classwork-view' id class_id test.id%}">DELETE</a></h3>
    <!-- {% for question in test.question_set.all%}
    <p>{{forloop.counter}}.{{question.question}}</p>
    {% if question.is_written %}
    {% else %}
    {% for option in question.multiplechoiceoption_set.all %}
    <ul>
    {%if option.is_true%}
      <li><strong>{{option.option}}</strong></li>
    {%else%}
      <li>{{option.option}}</li>
    {%endif%}
    </ul>
    {%endfor%}
    {%endif%}
    {%endfor%} -->
    {%endfor%}
    <a href="{% url 'create-classwork-view' id class_id%}">Create new test</a>
    <div>
      <a href="{% url 'lecturer-class-assignment-page' id class_id %}">Go back to class view</a>
    </div>
  {% endblock body %}