Courses/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from django.views.static import serve

urlpatterns = [
    path('student/<int:id>/class/<int:class_id>/feedback', views.StudentClassFeedback, name='student-class-feedback-page'),
    path('student/<int:id>/class/<int:class_id>/announcement', views.StudentClassAnnouncement, name='student-class-announcement-page'),
    path('student/<int:id>/class/<int:class_id>/content', views.StudentClassContent, name='student-class-content-page'),
    path('student<int:id>/class/<int:class_id>/content/<int:content_id>/download/', views.Download, name='student-download-content'),
    path('student/<int:id>/class/<int:class_id>/grade', views.StudentClassGrade, name='student-class-grade-page'),
    path('student/<int:id>/class/<int:class_id>/assignment', views.StudentClassAssignment, name='student-class-assignment-page'),
    path('student/<int:id>/registration', views.ClassRegistration, name='student-class-registration-page'),
    path('student/<int:id>/edit-registration', views.EditClassRegistration, name='edit-class-registration-page'),
    path('student/<int:id>/class/<int:class_id>/staff-contact/', views.StaffContact, name='student-staff-contact-page'),
    path('student/<int:id>/class/<int:class_id>/classwork/',include('Classwork.urls')),
    path('student/<int:id>/class/<int:class_id>/performance', views.ViewSelfCoursePerformance, name='student-view-self-course-performance'),
    path('lecturer/<int:id>/class/<int:class_id>/announcement', views.LecturerClassAnnouncement, name='lecturer-class-announcement-page'),
    path('lecturer/<int:id>/class/<int:class_id>/content', views.LecturerClassContent, name='lecturer-class-content-page'),
    path('lecturer<int:id>/class/<int:class_id>/content/<int:content_id>/download/', views.Download, name='lecturer-download-content'),
    path('lecturer/<int:id>/class/<int:class_id>/classwork/',include('Classwork.urls')),
    path('lecturer/<int:id>/class/<int:class_id>/grade', views.LecturerClassGrade, name='lecturer-class-grade-page'),
    path('lecturer/<int:id>/class/<int:class_id>/assignment', views.LecturerClassAssignment, name='lecturer-class-assignment-page'),
    path('lecturer/<int:id>/class/<int:class_id>/upload-class-announcement/', views.UploadClassAnnouncement, name='upload-class-announcement-page'),
    path('lecturer/<int:id>/class/<int:class_id>/<int:announcement_id>/edit/', views.EditClassAnnouncement, name='edit-class-announcement-page'),
    path('lecturer/<int:id>/class/<int:class_id>/upload-class-content/', views.UploadClassContent, name='upload-class-content-page'),
    path('lecturer/<int:id>/class/<int:class_id>/content/<int:content_id>/edit', views.EditClassContent, name='edit-class-content-page'),
    path('lecturer/<int:id>/class/<int:class_id>/staff-contact/', views.StaffContact, name='lecturer-staff-contact-page'),
    path('lecturer/<int:id>/class/<int:class_id>/student-list/', views.ViewStudentList, name='lecturer-class-view-student-list'),
    path('lecturer/<int:id>/class/<int:class_id>/student/<int:student_id>/performance', views.ViewStudentCoursePerformance, name='lecturer-view-student-course-performance'),
    path('lecturer/<int:id>/class/<int:class_id>/feedback', views.LecturerClassFeedback, name='lecturer-class-feedback-page'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_URL)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_URL)

Home/urls.py
from . import views
from django.urls import path,include

urlpatterns = [
    path('', views.GuestAnnouncement, name="guest-announcement-page"),
    path('user/', include("User.urls")),
    path('announcement/<int:announcement_id>', views.GuestAnnouncementPage, name='guest-announcement-viewpage'),
    path('about/', views.About, name='about'),
    path('about/talents', views.Talents, name='talents'),
    path('contact-us/', views.Contact, name='contact'),
    path('announcement/all/', views.GuestAnnouncementAll, name='guest-announcement-all'),
    path('announcement/search/', views.GuestAnnouncementSearch, name='guest-announcement-search'),
]

User/urls.py
from django.urls import path, include
from . import views
from Courses import views as coursesViews

urlpatterns = [
    path('login/',views.LoginView,name="login"),
    path('logout/',views.LogoutView,name="logout"),
    path('forgot/', views.ForgotPasswordView, name="forgot-password"),
    path('forgot/success/', views.ForgotPasswordSuccessView, name="forgot-password-success"),
    path('lecturer/<int:id>/about/', views.LecturerAboutView, name="lecturer-about"),
    path('lecturer/<int:id>/change-password/', views.LecturerChangePassword, name="lecturer-change-password"),
    path('lecturer/<int:id>/change-password/success', views.ChangePasswordSuccessView, name="lecturer-change-password-success"),
    path('lecturer/<int:id>/announcement/', views.LecturerUserAnnouncement, name="lecturer-announcement-page"),
    path('lecturer/<int:id>/announcement/general/all', views.LecturerGeneralAnnouncementViewAll, name="lecturer-general-announcement-all"),
    path('lecturer/<int:id>/announcement/class/all', views.LecturerClassAnnouncementViewAll, name="lecturer-class-announcement-all"),
    path('lecturer/<int:id>/announcement/<int:announcement_id>', views.LecturerGeneralAnnouncementPage, name="lecturer-general-announcement-page"),
    path('lecturer/<int:id>/active-classes/', coursesViews.ActiveLecturerClasses, name="active-lecturer-classes-page"),
    path('lecturer/<int:id>/calendar/', coursesViews.LecturerSchedule, name="lecturer-schedule-page"),
    path('student/<int:id>/about/', views.StudentAboutView, name="student-about"),
    path('student/<int:id>/change-password/', views.StudentChangePassword, name="student-change-password"),
    path('student/<int:id>/change-password/success', views.ChangePasswordSuccessView, name="student-change-password-success"),
    path('student/<int:id>/announcement/', views.StudentUserAnnouncement, name="student-announcement-page"),
    path('student/<int:id>/announcement/general/all', views.StudentGeneralAnnouncementViewAll, name="student-general-announcement-all"),
    path('student/<int:id>/announcement/class/all', views.StudentClassAnnouncementViewAll, name="student-class-announcement-all"),
    path('student/<int:id>/announcement/<int:announcement_id>', views.StudentGeneralAnnouncementPage, name="student-general-announcement-page"),
    path('student/<int:id>/active-classes/', coursesViews.ActiveStudentClasses, name="active-student-classes-page"),
    path('student/<int:id>/calendar/', coursesViews.StudentSchedule, name="student-schedule-page"),
    path('', include("Courses.urls")),
]

elearningplatform/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
import Courses.views as views
from django.views.static import serve


urlpatterns = [
    path('admin/', admin.site.urls,name="admin"),
    path('',include("Home.urls")),
    #path('user/',include("User.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_URL)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_URL)

Courses/models.py
import datetime

import pytz
from django.db import models
from django.db.models import CASCADE, SET_NULL
from User.models import Lecturer

# Create your models here.
class Major(models.Model):
    name = models.CharField(max_length=50)
    def __str__(self):
        return self.name


class Course(models.Model):
    major = models.ManyToManyField(Major)
    name = models.CharField(max_length=80)

    def __str__(self):
        return self.name


class Schedule(models.Model):
    DAYS_OF_WEEK = [
        ('MON', 'Monday'),
        ('TUE', 'Tuesday'),
        ('WED', 'Wednesday'),
        ('THU', 'Thursday'),
        ('FRI', 'Friday'),
        ('SAT', 'Saturday'),
        ('SUN', 'Sunday'),
    ]
    day_of_the_week = models.CharField(max_length=3, choices=DAYS_OF_WEEK)
    start_time = models.TimeField(auto_now=False, auto_now_add=False)
    duration = models.DurationField()

    @property
    def day_part(self):
        if (self.start_time <= datetime.time(12)):
            return 'Morning'
        else:
            return 'Afternoon'

    def __str__(self):
        return self.day_of_the_week + " " + self.day_part

    class Meta:
        pass
        #ordering = ['day_of_the_week', 'start_time']


class Class(models.Model):
    course = models.ForeignKey(Course, on_delete=CASCADE)
    lecturer = models.ForeignKey(Lecturer, on_delete=CASCADE)
    schedule = models.ForeignKey(Schedule, on_delete=SET_NULL, null=True,blank=True)
    start_date = models.DateTimeField(default=datetime.datetime(2021, 9, 6))

    def __str__(self):
        if self.schedule:
            return self.course.name + " - " + str(self.schedule) + " - " + self.lecturer.user_id.full_name + " -  " + self.sem_year
        else:
            return self.course.name + "-" + self.lecturer.user_id.full_name

    @property
    def month(self):
        return int(self.start_date.strftime("%m"))

    @property
    def year(self):
        return int(self.start_date.strftime("%Y"))

    @property
    def sem_year(self):
        year = self.year
        month = self.month
        if month in [9, 10, 11, 12, 1]:
            return "Sem 1 - {}".format(year + 1)
        elif month in [2, 3, 4, 5, 6]:
            return "Sem 2 - {}".format(int(year))

    @property
    def is_displayable(self):
        utc = pytz.UTC
        now = utc.localize(datetime.datetime.now())
        if (now < self.start_date):
            return False
        else:
            return True


class ClassAnnouncement(models.Model):
    class_id = models.ForeignKey(Class, on_delete=CASCADE)
    title = models.CharField(max_length=255)
    time_created = models.DateTimeField(auto_now_add=False)
    time_modified = models.DateTimeField(auto_now=True)
    content = models.TextField()

    @property
    def is_displayable(self):
        utc = pytz.UTC
        if self.time_created > utc.localize(datetime.datetime.now()):
            return False
        else:
            return True

    def __save__(self):
        self.time_created = datetime.now()

    class Meta:
        ordering = ["time_created", "time_modified"]


class ClassContent(models.Model):
    class_id = models.ForeignKey(Class, on_delete=CASCADE)
    title = models.CharField(max_length=255)
    time_created = models.DateTimeField(auto_now_add=False)
    time_modified = models.DateTimeField(auto_now=True)
    attached_file = models.FileField(upload_to='', blank=True)
    content = models.TextField(blank=True)

    @property
    def is_displayable(self):
        utc = pytz.UTC
        if self.time_created > utc.localize(datetime.datetime.now()):
            return False
        else:
            return True

    @property
    def file_url(self):
        if self.attached_file and hasattr(self.attached_file, 'url'):
            return self.attached_file.url

    def __save__(self):
        self.time_created = datetime.now()

    class Meta:
        ordering = ["time_created", "time_modified"]


class ClassFeedback(models.Model):
    class_id = models.ForeignKey(Class, on_delete=CASCADE)
    content = models.TextField(max_length=1000, blank=False)
    time_created = models.DateTimeField(auto_now_add=True)

Courses/forms.py
import pytz

from Courses.models import ClassAnnouncement, ClassContent, Class, ClassFeedback
from django import forms
from django.core.exceptions import ValidationError
from datetime import datetime, timedelta

utc = pytz.UTC

class UploadClassAnnouncementForm(forms.ModelForm):
    title = forms.CharField(label='Title', widget=forms.TextInput(attrs={'placeholder': 'Announcement Title'}))
    content = forms.CharField(label='Content', widget=forms.Textarea(
        attrs={'placeholder': 'Announcement Content'}))
    time_created = forms.DateTimeField(label='Time displayed', widget=forms.DateTimeInput(attrs={'type': 'datetime-local'}))

    def clean_time_created(self):
        time_created = self.cleaned_data['time_created']
        if time_created < utc.localize(datetime.now()):
            raise forms.ValidationError("Time displayed must not be in the past.")
        elif time_created > utc.localize(datetime.now() + timedelta(days=7)):
            raise forms.ValidationError("Only choose display time within this week.")
        return time_created

    class Meta:
        model = ClassAnnouncement
        fields = [
            'title',
            'content',
            'time_created'
        ]


class UploadClassContentForm(forms.ModelForm):
    title = forms.CharField(label='Title', widget=forms.TextInput(attrs={'placeholder': 'Content Title'}))
    content = forms.CharField(label='Description', widget=forms.Textarea(
        attrs={'placeholder': 'Content Description'}))
    time_created = forms.DateTimeField(label='Time displayed', widget=forms.DateTimeInput(attrs={'type': 'datetime-local'}))

    def clean_time_created(self):
        time_created = self.cleaned_data['time_created']
        if time_created < utc.localize(datetime.now()):
            raise forms.ValidationError("Time displayed must not be in the past.")
        elif time_created > utc.localize(datetime.now() + timedelta(days=7)):
            raise forms.ValidationError("Only choose display time within this week.")
        return time_created

    class Meta:
        model = ClassContent
        fields = [
            'attached_file',
            'title',
            'content',
            'time_created'
        ]


class ClassRegistrationForm(forms.Form):
    def __init__(self, *args, **kwargs):
        choices = kwargs.pop('choices')
        super(ClassRegistrationForm,self).__init__(*args, **kwargs)
        self.fields['selection'] = forms.MultipleChoiceField(choices=choices,widget=forms.CheckboxSelectMultiple)

    def clean_selection(self):
        selection = self.cleaned_data['selection']
        duplicates = any(selection.choice_label.count(i) for i in selection.choice_label)
        if duplicates > 0:
            raise forms.ValidationError('Dup')
        return selection

    class Meta:
        model = Class


class EditClassRegistrationForm(forms.Form):
    selection = forms.BooleanField(widget=forms.CheckboxSelectMultiple)


class EditClassAnnouncementForm(forms.ModelForm):
    title = forms.CharField(label='Title', widget=forms.TextInput(attrs={'placeholder': 'Announcement Title'}))
    content = forms.CharField(label='Content', widget=forms.Textarea(attrs={'placeholder': 'Announcement Content'}))

    class Meta:
        model = ClassAnnouncement
        fields = ['title', 'content']


class EditClassContentForm(forms.ModelForm):
    title = forms.CharField(label='Title', widget=forms.TextInput(attrs={'placeholder': 'Content Title'}))
    content = forms.CharField(label='Description', widget=forms.Textarea(attrs={'placeholder': 'Content Description'}))
    attached_file = forms.FileField(label='File', required=False, widget=forms.ClearableFileInput(attrs={'allow_multiple_selected':True}))
    class Meta:
        model = ClassContent
        fields = ['attached_file', 'title', 'content']


class UploadClassFeedbackForm(forms.ModelForm):
    content = forms.CharField(label='Content', widget=forms.Textarea(attrs={'placeholder': '...'}))

    class Meta:
        model = ClassFeedback
        fields = ['content']

User/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm, UsernameField

class PasswordResetForm(forms.Form):
    email = forms.EmailField()
    first_name = forms.CharField(max_length=50)
    # add morjor field when implemented
    new_password = forms.CharField(max_length=50, widget=forms.PasswordInput)
    confirm_password = forms.CharField(
        max_length=50, widget=forms.PasswordInput)

    def clean(self):
        cleaned_data = super(PasswordResetForm, self).clean()
        new_password = cleaned_data.get("new_password")
        confirm_password = cleaned_data.get("confirm_password")
        if new_password != confirm_password:
            raise forms.ValidationError(
                "password and confirm_password does not match"
            )
        return cleaned_data


class LoginForm(AuthenticationForm):
    class Meta:
        widgets = {
            'id_username': forms.TextInput(attrs={'placeholder':'username','class':'user','size':25,'maxlength':50,'autocomplete':'off','required':'required'})
        }

Courses/templates/User/class-registration.html
{% extends 'Home/index.html' %}
{% load static %}

{% block title %}
  <title>Course Registration</title>
{% endblock title %}

{% block stylesheets %}
  <link rel="stylesheet" href="{% static 'User/class-registration.css' %}">
  <script defer src="{% static 'User/class-registration.js' %}"></script>
{% endblock %}

{% block registration-active %}active{% endblock %}

{% block main-content %}
<article class="panel registration">
  <h2>Class Registration</h2>
  <div class="search">
    <label for="search">
      <svg width="18" height="18" viewBox="0 0 18 18" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
        <path d="M12.4996 11H11.7096L11.4296 10.73C12.6296 9.33002 13.2496 7.42002 12.9096 5.39002C12.4396 2.61002 10.1196 0.390015 7.31965 0.0500152C3.08965 -0.469985 -0.470351 3.09001 0.049649 7.32001C0.389649 10.12 2.60965 12.44 5.38965 12.91C7.41965 13.25 9.32965 12.63 10.7296 11.43L10.9996 11.71V12.5L15.2496 16.75C15.6596 17.16 16.3296 17.16 16.7396 16.75C17.1496 16.34 17.1496 15.67 16.7396 15.26L12.4996 11ZM6.49965 11C4.00965 11 1.99965 8.99002 1.99965 6.50002C1.99965 4.01002 4.00965 2.00002 6.49965 2.00002C8.98965 2.00002 10.9996 4.01002 10.9996 6.50002C10.9996 8.99002 8.98965 11 6.49965 11Z"
              fill="currentColor"/>
      </svg>
    </label>
    <input type="search" id="search" placeholder="Search for courses..">
  </div>
  <div>
    <h2>Deadline: {{ deadline }}</h2>
  </div>
  <form method="POST" action="{% url 'student-class-registration-page' student.id %}" enctype="multipart/form-data">
    {% csrf_token %}
      <div class="scrollable">
        <table id="class-table" class="class-table">
          <thead>
          <tr>
            <th>Select</th>
            <th class="subject-col">Subject name</th>
            <th>Class ID</th>
            <th>Semester</th>
            <th>Day</th>
            <th>Start time</th>
            <th>Duration</th>
            <th>Instructor</th>
          </tr>
          </thead>
          <tbody>
            {% for field in form %}
              {% for choice_id, choice_label in field.field.choices %}
                {% for class in classes %}
                  {% if class.id == choice_id %}
                      <tr>
                        <td><input type="checkbox" name="selection" value="{{ choice_id }}" id="{{ choice_id }}"
                                   {% if not is_past_deadline %}
                                     {% for student_class in student_classes %}
                                      {% if student_class.id == choice_id %}disabled
                                      {% elif student_class.course.name == choice_label %}disabled
                                      {% endif %}
                                     {% endfor %}
                                   {% elif is_past_deadline %}disabled
                                   {% endif %}></td>
                        <td>{{ choice_label }}</td>
                        <td>{{ choice_id }}</td>
                        <td>{{ class.sem_year }}</td>
                        <td>{{ class.schedule.get_day_of_the_week_display }}</td>
                        <td>{{ class.schedule.start_time }}</td>
                        <td>{{ class.schedule.duration }}</td>
                        <td>{{ class.lecturer.user_id.full_name }}</td>
                      </tr>
                  {% endif %}
                {% endfor %}
              {% endfor %}
            {% endfor %}
          </tbody>
        </table>
      </div>
    <button id="submit" class="btn submit">Register</button>
    <a class="btn-edit" href="{% url 'edit-class-registration-page' student.id %}">Edit registered classes</a>
  </form>
</article>
{% endblock %}

Courses/templates/User/edit-class-announcement.html
{% extends 'Courses/base-class-course.html' %}
{% load static %}

{% block title %}
  <title>{{ lecturer_class.course.name }} - {{ lecturer_class.schedule }} Edit announcement</title>
{% endblock title %}

{% block stylesheets %}
  {{ block.super }}
  <link rel="stylesheet" href="{% static 'User/base-upload.css' %}">
  <link rel="stylesheet" href="{% static 'User/upload-announcement.css' %}">
{% endblock %}

{% block tabs_navbar %}{% endblock tabs_navbar %}

{% block panel-content %}
  <article>
    <form action="{% url 'edit-class-announcement-page' lecturer.id lecturer_class.id announcement.id %}" method="POST" enctype="multipart/form-data">
      {% csrf_token %}
      {{ form.as_p }}
      <div class="heading">
        <h3 class="title"></h3>
      </div>
      <div class="btn-container">
        <input class="btn-delete" name="delete_button" type="Submit" value="Delete" href="{% url 'lecturer-class-announcement-page' lecturer.id lecturer_class.id %}"/>
        <div class="right-buttons">
        <input class="btn post" name="post_button" type="Submit" value="Post"/>
        <a class="btn cancel" href="{% url 'lecturer-class-announcement-page' lecturer.id lecturer_class.id %}">
          Cancel
        </a>
      </div>
    </form>
  </article>
{% endblock %}

Courses/templates/User/edit-class-content.html
{% extends 'Courses/base-class-course.html' %}
{% load static %}

{% block title %}
  <title>{{ lecturer_class.course.name }} - {{ lecturer_class.schedule }} Edit content</title>
{% endblock title %}

{% block stylesheets %}
  {{ block.super }}
  <link rel="stylesheet" href="{% static 'User/base-upload.css' %}">
  <link rel="stylesheet" href="{% static 'User/upload-announcement.css' %}">
  <script src="{% static 'User/upload-content.js' %}" defer></script>
{% endblock %}

{% block tabs_navbar %}{% endblock tabs_navbar %}

{% block panel-content %}
  <article>
    <div class="heading">
      <h3 class="title">Edit Content</h3>
    </div>
    <form method="POST" action="{% url 'edit-class-content-page' lecturer.id lecturer_class.id post.id %}" enctype="multipart/form-data">
      {% csrf_token %}
      {{ form.as_p }}
      <div class="btn-container">
        <input class="btn-delete" name="delete_button" type="Submit" value="Delete" href="{% url 'lecturer-class-content-page' lecturer.id lecturer_class.id %}">
        <div class="right-buttons">
        <input class="btn post" name="post_button" type="Submit" value="Post"/>
        <a class="btn cancel" href="{% url 'lecturer-class-content-page' lecturer.id lecturer_class.id %}">
          Cancel
        </a>
      </div>
    </form>
  </article>
{% endblock %}

Courses/templates/User/edit-class-registration.html
{% extends 'Home/index.html' %}
{% load static %}

{% block title %}
  <title>Edit Course Registration</title>
{% endblock title %}

{% block stylesheets %}
  <link rel="stylesheet" href="{% static 'User/class-registration.css' %}">
  <script defer src="{% static 'User/class-registration.js' %}"></script>
{% endblock %}

{% block registration-active %}active{% endblock %}

{% block main-content %}
<article class="panel registration">
  <h2>Class Registration</h2>
  <div class="search">
    <label for="search">
      <svg width="18" height="18" viewBox="0 0 18 18" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
        <path d="M12.4996 11H11.7096L11.4296 10.73C12.6296 9.33002 13.2496 7.42002 12.9096 5.39002C12.4396 2.61002 10.1196 0.390015 7.31965 0.0500152C3.08965 -0.469985 -0.470351 3.09001 0.049649 7.32001C0.389649 10.12 2.60965 12.44 5.38965 12.91C7.41965 13.25 9.32965 12.63 10.7296 11.43L10.9996 11.71V12.5L15.2496 16.75C15.6596 17.16 16.3296 17.16 16.7396 16.75C17.1496 16.34 17.1496 15.67 16.7396 15.26L12.4996 11ZM6.49965 11C4.00965 11 1.99965 8.99002 1.99965 6.50002C1.99965 4.01002 4.00965 2.00002 6.49965 2.00002C8.98965 2.00002 10.9996 4.01002 10.9996 6.50002C10.9996 8.99002 8.98965 11 6.49965 11Z"
              fill="currentColor"/>
      </svg>
    </label>
    <input type="search" id="search" placeholder="Search for courses..">
  </div>
  <div>
    <h2>Deadline: {{ deadline }}</h2>
  </div>
  <form method="POST" action="{% url 'edit-class-registration-page' student.id %}" enctype="multipart/form-data">
    {% csrf_token %}
      <div class="scrollable">
        <table id="class-table" class="class-table">
          <thead>
          <tr>
            <th>Select</th>
            <th class="subject-col">Subject name</th>
            <th>Class ID</th>
            <th>Semester</th>
            <th>Day</th>
            <th>Start time</th>
            <th>Duration</th>
            <th>Instructor</th>
          </tr>
          </thead>
          <tbody>
            {% for class in classes %}
              <tr>
                <td><input type="checkbox" name="selection" value="{{ class.id }}" {% if is_past_deadline %}disabled{% else %}checked="checked"{% endif %}></td>
                <th>{{ class.course.name }}</th>
                <th>{{ class.id }}</th>
                <th>{{ class.sem_year }}</th>
                <th>{{ class.schedule.day_of_the_week }}</th>
                <th>{{ class.schedule.start_time }}</th>
                <th>{{ class.schedule.duration }}</th>
                <th>{{ class.lecturer.user_id.full_name }}</th>
              </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
      {% if not is_past_deadline %}
        <button id="submit" class="btn submit">Submit</button>
      {% elif is_past_deadline %}
      {% endif %}
  </form>
</article>
{% endblock %}

Courses/templates/User/upload-announcement.html
{% extends 'Courses/base-class-course.html' %}
{% load static %}

{% block title %}
  <title>{{ lecturer_class.course.name }} - {{ lecturer_class.schedule }} Upload announcement</title>
{% endblock title %}

{% block stylesheets %}
  {{ block.super }}
  <link rel="stylesheet" href="{% static 'User/base-upload.css' %}">
  <link rel="stylesheet" href="{% static 'User/upload-announcement.css' %}">
{% endblock %}

{% block tabs_navbar %}{% endblock tabs_navbar %}

{% block panel-content %}
  <article>
    <div class="heading">
      <h3 class="title">New Announcement</h3>
    </div>
    <form action="." method="POST">
      {% csrf_token %}
      {{ form.as_p }}
      <div class="btn-container">
        <a class="btn cancel" href="{% url 'lecturer-class-announcement-page' lecturer.id lecturer_class.id %}">
          Cancel
        </a>
        <input class="btn post" type="Submit" value="Post"/>
      </div>
    </form>
  </article>
{% endblock %}

Courses/templates/User/upload-content.html
{% extends 'Courses/base-class-course.html' %}
{% load static %}

{% block title %}
  <title>{{ lecturer_class.course.name }} - {{ lecturer_class.schedule }} Upload content</title>
{% endblock title %}

{% block stylesheets %}
  {{ block.super }}
  <link rel="stylesheet" href="{% static 'User/base-upload.css' %}">
  <link rel="stylesheet" href="{% static 'User/upload-announcement.css' %}">
  <script src="{% static 'User/upload-content.js' %}" defer></script>
{% endblock %}

{% block tabs_navbar %}{% endblock tabs_navbar %}

{% block panel-content %}
  <article>
    <div class="heading">
      <h3 class="title">New Content</h3>
    </div>
    <form action="." method="POST" enctype="multipart/form-data">
      {% csrf_token %}
      {{ form.as_p }}
      <div class="btn-container">
        <a class="btn cancel" href="{% url 'lecturer-class-content-page' lecturer.id lecturer_class.id %}">
          Cancel
        </a>
        <input class="btn post" type="Submit" value="Post"/>
      </div>
    </form>
  </article>
{% endblock %}